<a href="https://colab.research.google.com/github/felexkuria/Data-Analysyis-using-Python/blob/master/Data_Wrangling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

students = pd.DataFrame({
    "Student_ID": [101, 102, 103],
    "Name": ["Mary", "John", "Amina"]
})

scores = pd.DataFrame({
    "Student_ID": [101, 103, 104],
    "Score": [80, 90, 75]
})

print(students)
print(scores)

   Student_ID   Name
0         101   Mary
1         102   John
2         103  Amina
   Student_ID  Score
0         101     80
1         103     90
2         104     75

In [ ]:
pd.merge(students, scores, on="Student_ID", how="right")

   Student_ID   Name  Score
0         101   Mary     80
1         103  Amina     90
2         104    NaN     75

In [ ]:
pd.merge(students,scores,on='Student_ID',how='inner')

   Student_ID   Name  Score
0         101   Mary     80
1         103  Amina     90

In [ ]:
pd.merge(students,scores,on='Student_ID',how='left')

   Student_ID   Name  Score
0         101   Mary   80.0
1         102   John    NaN
2         103  Amina   90.0

In [ ]:
pd.merge(students,scores,on='Student_ID',how='outer')

   Student_ID   Name  Score
0         101   Mary   80.0
1         102   John    NaN
2         103  Amina   90.0
3         104    NaN   75.0

In [ ]:


# DataFrame 1: Customers
data_customers = {
    'CustomerID': [101, 102, 103, 104, 105],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'City': ['New York', 'London', 'Paris', 'New York', 'Tokyo']
}
df_customers = pd.DataFrame(data_customers)

# DataFrame 2: Orders
# Note:
# - CustomerID 101 and 102 have orders (will match inner)
# - CustomerID 106 exists in orders but not customers (will be seen in right/outer)
# - CustomerID 103, 104, 105 exist in customers but have no orders (will be seen in left/outer)
data_orders = {
    'OrderID': ['ORD001', 'ORD002', 'ORD003', 'ORD004', 'ORD005'],
    'CustomerID': [101, 102, 101, 106, 102],
    'Product': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Webcam'],
    'Quantity': [1, 2, 1, 1, 1]
}
df_orders = pd.DataFrame(data_orders)

print("--- df_customers ---")
print(df_customers)
print("\n--- df_orders ---")
print(df_orders)

--- df_customers ---
   CustomerID     Name      City
0         101    Alice  New York
1         102      Bob    London
2         103  Charlie     Paris
3         104    David  New York
4         105      Eve     Tokyo

--- df_orders ---
  OrderID  CustomerID   Product  Quantity
0  ORD001         101    Laptop         1
1  ORD002         102     Mouse         2
2  ORD003         101  Keyboard         1
3  ORD004         106   Monitor         1
4  ORD005         102    Webcam         1

In [ ]:
df_customers.merge(df_orders, on='CustomerID', how='inner')

   CustomerID   Name      City OrderID   Product  Quantity
0         101  Alice  New York  ORD001    Laptop         1
1         101  Alice  New York  ORD003  Keyboard         1
2         102    Bob    London  ORD002     Mouse         2
3         102    Bob    London  ORD005    Webcam         1

In [ ]:
pd.merge(df_customers,df_orders,on='CustomerID',how='right')

   CustomerID   Name      City OrderID   Product  Quantity
0         101  Alice  New York  ORD001    Laptop         1
1         102    Bob    London  ORD002     Mouse         2
2         101  Alice  New York  ORD003  Keyboard         1
3         106    NaN       NaN  ORD004   Monitor         1
4         102    Bob    London  ORD005    Webcam         1

In [ ]:
pd.merge(df_customers,df_orders,on='CustomerID',how='left')

   CustomerID     Name      City OrderID   Product  Quantity
0         101    Alice  New York  ORD001    Laptop       1.0
1         101    Alice  New York  ORD003  Keyboard       1.0
2         102      Bob    London  ORD002     Mouse       2.0
3         102      Bob    London  ORD005    Webcam       1.0
4         103  Charlie     Paris     NaN       NaN       NaN
5         104    David  New York     NaN       NaN       NaN
6         105      Eve     Tokyo     NaN       NaN       NaN

In [ ]:
pd.merge(df_customers,df_orders,on='CustomerID',how='outer')

   CustomerID     Name      City OrderID   Product  Quantity
0         101    Alice  New York  ORD001    Laptop       1.0
1         101    Alice  New York  ORD003  Keyboard       1.0
2         102      Bob    London  ORD002     Mouse       2.0
3         102      Bob    London  ORD005    Webcam       1.0
4         103  Charlie     Paris     NaN       NaN       NaN
5         104    David  New York     NaN       NaN       NaN
6         105      Eve     Tokyo     NaN       NaN       NaN
7         106      NaN       NaN  ORD004   Monitor       1.0

In [ ]:
pd.merge(df_orders,df_customers,on='CustomerID',how='outer')

  OrderID  CustomerID   Product  Quantity     Name      City
0  ORD001         101    Laptop       1.0    Alice  New York
1  ORD003         101  Keyboard       1.0    Alice  New York
2  ORD002         102     Mouse       2.0      Bob    London
3  ORD005         102    Webcam       1.0      Bob    London
4     NaN         103       NaN       NaN  Charlie     Paris
5     NaN         104       NaN       NaN    David  New York
6     NaN         105       NaN       NaN      Eve     Tokyo
7  ORD004         106   Monitor       1.0      NaN       NaN

In [ ]:
import numpy as np
a=np.random.default_rng().integers

In [ ]:
matrixa=a(10,size=(2,2))

In [ ]:
# Example square matrix
matrix = np.array([[1, 2], [2, 1]])

# Correct function to compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrixa)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [10.16227766  3.83772234]
Eigenvectors:
 [[ 0.9817497  -0.75804292]
 [ 0.19017762  0.65220467]]

In [2]:
import numpy as np
a=np.ones((2, 2))
np.argmax(a)

np.int64(0)